interface ZIF_V_VENDAITEM_XXX_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ZV_VENDAITEM_XXX,
 CREATE_ZV_VENDAITEM_XXX        TYPE /BOBF/ACT_KEY VALUE '0800274311021EDA88986880BE8E1F9F',
 DELETE_ZV_VENDAITEM_XXX        TYPE /BOBF/ACT_KEY VALUE '0800274311021EDA88986880BE8E9F9F',
 LOCK_ZV_VENDAITEM_XXX          TYPE /BOBF/ACT_KEY VALUE '0800274311021EDA88986880BE8D5F9F',
 SAVE_ZV_VENDAITEM_XXX          TYPE /BOBF/ACT_KEY VALUE '0800274311021EDA88986880BE8F1F9F',
 UNLOCK_ZV_VENDAITEM_XXX        TYPE /BOBF/ACT_KEY VALUE '0800274311021EDA88986880BE8D9F9F',
 UPDATE_ZV_VENDAITEM_XXX        TYPE /BOBF/ACT_KEY VALUE '0800274311021EDA88986880BE8E5F9F',
 VALIDATE_ZV_VENDAITEM_XXX      TYPE /BOBF/ACT_KEY VALUE '0800274311021EDA88986880BE8EDF9F',
      END OF ZV_VENDAITEM_XXX,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ZV_VENDAITEM_XXX,
        BEGIN OF LOCK_ZV_VENDAITEM_XXX,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
        END OF LOCK_ZV_VENDAITEM_XXX,
        BEGIN OF UNLOCK_ZV_VENDAITEM_XXX,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
        END OF UNLOCK_ZV_VENDAITEM_XXX,
      END OF ZV_VENDAITEM_XXX,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ALTERNATIVE_KEY,
      BEGIN OF ZV_VENDAITEM_XXX,
 DB_KEY                         TYPE /BOBF/OBM_ALTKEY_KEY VALUE '0800274311021EDA88986880BE8FFF9F',
      END OF ZV_VENDAITEM_XXX,
    END OF SC_ALTERNATIVE_KEY .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ZV_VENDAITEM_XXX,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE '0800274311021EDA88986880BE8D3F9F',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE '0800274311021EDA88986880BE8CFF9F',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE '0800274311021EDA88986880BE8DFF9F',
      END OF ZV_VENDAITEM_XXX,
      BEGIN OF ZV_VENDAITEM_XXX_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '0800274311021EDA88986880BE8F7F9F',
      END OF ZV_VENDAITEM_XXX_LOCK,
      BEGIN OF ZV_VENDAITEM_XXX_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '0800274311021EDA88986880BE8F5F9F',
      END OF ZV_VENDAITEM_XXX_MESSAGE,
      BEGIN OF ZV_VENDAITEM_XXX_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '0800274311021EDA88986880BE8F9F9F',
      END OF ZV_VENDAITEM_XXX_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ZV_VENDAITEM_XXX,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ZV_VENDAITEM_XXX,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE '0800274311021EDA88986880BE8C5F9F' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZV_VENDAITEM_XXX' .
  constants:
    BEGIN OF SC_DETERMINATION,
      BEGIN OF ZV_VENDAITEM_XXX,
 ACTION_AND_FIELD_CONTROL       TYPE /BOBF/DET_KEY VALUE '0800274311021EDA88986880BE901F9F',
      END OF ZV_VENDAITEM_XXX,
    END OF SC_DETERMINATION .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ZV_VENDAITEM_XXX               TYPE /BOBF/OBM_NODE_KEY VALUE '0800274311021EDA88986880BE8C9F9F',
 ZV_VENDAITEM_XXX_LOCK          TYPE /BOBF/OBM_NODE_KEY VALUE '0800274311021EDA88986880BE8D1F9F',
 ZV_VENDAITEM_XXX_MESSAGE       TYPE /BOBF/OBM_NODE_KEY VALUE '0800274311021EDA88986880BE8CDF9F',
 ZV_VENDAITEM_XXX_PROPERTY      TYPE /BOBF/OBM_NODE_KEY VALUE '0800274311021EDA88986880BE8DDF9F',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ZV_VENDAITEM_XXX,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  ID                             TYPE STRING VALUE 'ID',
  MATERIAL                       TYPE STRING VALUE 'MATERIAL',
  QUANTIDADE                     TYPE STRING VALUE 'QUANTIDADE',
  UNID_MEDIDA                    TYPE STRING VALUE 'UNID_MEDIDA',
  VALOR                          TYPE STRING VALUE 'VALOR',
  CURR                           TYPE STRING VALUE 'CURR',
  TARGETCURR                     TYPE STRING VALUE 'TARGETCURR',
  CONVERTEDGROSSAMOUNT           TYPE STRING VALUE 'CONVERTEDGROSSAMOUNT',
      END OF ZV_VENDAITEM_XXX,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ZV_VENDAITEM_XXX,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE '0800274311021EDA88986880BE8CBF9F',
      END OF ZV_VENDAITEM_XXX,
    END OF SC_NODE_CATEGORY .
endinterface.
